name: Continuous Integration

on:
    push:
    pull_request:
        branches:
            - main
        paths-ignore:
            - "**.md"
            - ".env.template"
            - ".gitattributes"
            - ".gitignore"

env:
    CARGO_TERM_COLOR: always
    CARGO_INCREMENTAL: 0
    RUST_BACKTRACE: 1

jobs:
    format_and_lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: stable
                  components: rustfmt, clippy

            - name: Run cargo fmt
              run: cargo fmt --all -- --check

            - name: Run Clippy
              run: cargo clippy --all --all-features --tests -- -D warnings

    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: stable

            - name: Run Tests
              run: cargo test --all-features
